version: '3.4'

services:
  # productservice:
  #   restart: always
  #   build:
  #     context: ./Backend
  #     dockerfile: ProductService/Dockerfile
  #   ports:
  #     - 5005:5000
  #   depends_on:
  #      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5006:5432
    volumes:
      - /Docker/ProductDB:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: pass
        POSTGRES_USER: user
        POSTGRES_DB: ProductDB