version: 1
jobs:
  backend_build:
    docker:
      - image: microsoft/dotnet:2.2.100-sdk-stretch
    steps:
      - checkout
      - run: cd Backend && dotnet restore
      - run: cd Backend && dotnet build
  backend_test:
    docker:
      - image: microsoft/dotnet:2.2.100-sdk-stretch
    steps:
      - checkout
      - run: cd Backend && dotnet test -r results
  backend_publish:
    docker:
      - image: microsoft/dotnet:2.2.100-sdk-stretch
    steps:
      - checkout
      - run: cd Backend && dotnet publish -c Release
  frontend_build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run: cd Frontend && npm i
      - run: cd Frontend && npm run build
  frontend_test:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run: cd Frontend && npm i
      - run: cd Frontend && npm run test

workflows:
  version: 2
  build:
    jobs:
      - backend_build
      - backend_test:
          requires:
            - backend_build
      - backend_publish:
          requires:
            - backend_build
      - frontend_build